version: "3"

# Try `docker-compose up`

services:
    ovpn_proxy:
        image: jonoh/openvpn-proxy
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun
        dns:
            - 1.1.1.1
            - 1.0.0.1
        volumes:
            - ./config.ovpn:/config/config.ovpn
        environment: # This needs to change - your local network(s)
            - LOCAL_NETWORK=10.0.8.1/24
            # For multiple networks: LOCAL_NETWORK=10.0.8.0/24,192.168.1.0/24
            # Create a .env file with these values
            - OPENVPN_USERNAME=${OPENVPN_USERNAME}
            - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
            # Adjust for your needs
            - OPENVPN_TUNNEL_HOSTS=*.corp.com
        ports:
            - 8081:80
            - 8080:8080
        restart: always
