version: "3"

# Try `docker-compose up`

services:
    ovpn_proxy:
        image: ghcr.io/paul-k-online/docker-openvpn-proxy:latest
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun
        dns:
            - 1.1.1.1
            - 1.0.0.1
        volumes:
            - ./config.ovpn:/config/config.ovpn
        environment: # This needs to change - your local network
            - LOCAL_NETWORK=10.0.8.1/24
            # Create a .env file with these values
            - OPENVPN_USERNAME=${OPENVPN_USERNAME}
            - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
            # Adjust for your needs
            - OPENVPN_TUNNEL_HOSTS=*.corp.com
            # Optional: additional OpenVPN arguments
            # - OPENVPN_EXTRA_ARGS=--verb 3 --log /tmp/openvpn.log
        ports:
            - 8081:80
            - 8080:8080
        restart: always
